# An example of the most basic config file we can use with `MKDocs`
# Great place to start to see if this is working / what you need to fix
# or customzie

site_name: Majeed's Quantum Notes
site_url: https://majeedtanveer.github.io/quantum-info
site_author: Majeed Tanveer
site_description: A description of your site

# Source directory (where your markdown files are)
docs_dir: .site_content

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# Add MathJax For LaTeX
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js